[install]
neovim.pkg-path = "neovim"
tig.pkg-path = "tig"
git.pkg-path = "git"
tmux.pkg-path = "tmux"
curl.pkg-path = "curl"
direnv.pkg-path = "direnv"
which.pkg-path = "which"
nodejs_20.pkg-path = "nodejs_20"
ripgrep.pkg-path = "ripgrep"

[options]
systems = ["x86_64-linux"]
